name: CI IM Node

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Download and extract era-test-node binary
        run: |
          wget https://github.com/matter-labs/era-test-node/releases/download/v0.1.0/era_test_node-v0.1.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf era_test_node-v0.1.0-x86_64-unknown-linux-gnu.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Start era-test-node binary
        run: |
          ./era_test_node &
          sleep 10

      - run: yarn test:fork
        env:
          ZKSYNC_PRIVATE_KEY: "0x7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110"
          ZKSYNC_WEB3_API_URL: "http://127.0.0.1:8011"

      - name: Stop era-test-node
        run: pkill era_test_node
