name: CI Docker Local

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t my-era-test-node ./docker/era-test-node-binary/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/docker-image-cacher

      - name: Start era-test-node
        run: |
          docker run -d --name era-test-node -p 8011:8011 my-era-test-node
          sleep 10

      - run: yarn test:fork
        env:
          ZKSYNC_PRIVATE_KEY: "0x7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110"
          ZKSYNC_WEB3_API_URL: "http://127.0.0.1:8011"

      - name: Stop era-test-node
        run: docker stop era-test-node
