name: CI Docker Local Binary

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-era-test-node ./docker/era-test-node-binary/
      - name: Save Docker image
        run: docker save my-era-test-node:latest > my-era-test-node.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: my-era-test-node-image
          path: my-era-test-node.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: my-era-test-node-image
      - name: Load Docker image
        run: docker load < my-era-test-node.tar
      - name: Start era-test-node
        run: |
          docker run -d --name era-test-node -p 8011:8011 my-era-test-node
          sleep 10
      - run: yarn test:fork
        env:
          ZKSYNC_PRIVATE_KEY: "0x7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110"
          ZKSYNC_WEB3_API_URL: "http://127.0.0.1:8011"
      - name: Stop era-test-node
        run: docker stop era-test-node
